# Generated by Django 4.1.7 on 2023-03-26 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('school_period', models.CharField(max_length=10)),
                ('sw_prosecution', models.BooleanField()),
                ('condition', models.CharField(choices=[('N/A', 'N/A'), ('RG', 'REGULAR'), ('NI', 'NUEVO INGRESO'), ('R', 'REPITIENTE')], max_length=5)),
                ('grade', models.CharField(choices=[('N/A', 'N/A'), ('1ER AÑO', '1ER AÑO'), ('2DO AÑO', '2DO AÑO'), ('3ER AÑO', '3ER AÑO'), ('4TO AÑO', '4TO AÑO'), ('5TO AÑO', '5TO AÑO')], max_length=20)),
                ('section', models.CharField(choices=[('N/A', 'N/A'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I')], max_length=5)),
                ('admission_date', models.DateField()),
                ('month_dat', models.CharField(choices=[('ENERO', 'ENERO'), ('FEBRERO', 'FEBRERO'), ('MARZO', 'MARZO'), ('ABRIL', 'ABRIL'), ('MAYO', 'MAYO'), ('JUNIO', 'JUNIO'), ('JULIO', 'JULIO'), ('AGOSTO', 'AGOSTO'), ('SEPTIEMBRE', 'SEPTIEMBRE'), ('OCTUBRE', 'OCTUBRE'), ('NOVIEMBRE', 'NOVIEMBRE'), ('DICIEMBRE', 'DICIEMBRE')], max_length=15)),
                ('system_date', models.DateField()),
                ('re_registration', models.BooleanField(default=False)),
                ('registration_type', models.CharField(max_length=10)),
                ('status', models.CharField(default='I', max_length=2)),
                ('observation', models.TextField()),
                ('enroller_name', models.CharField(max_length=150)),
                ('record_number', models.CharField(max_length=5)),
                ('institution_name', models.CharField(max_length=100)),
                ('institution_dea', models.CharField(max_length=50)),
                ('institution_cod_adm', models.CharField(max_length=100)),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.representative')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.estudent')),
            ],
        ),
    ]
