# Generated by Django 4.1.7 on 2023-03-25 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('identification_card', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('fn', models.DateField()),
                ('sex', models.CharField(choices=[('N/A', 'N/A'), ('M', 'Masculino'), ('F', 'Femenino')], max_length=3)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_staff', models.CharField(choices=[('N/A', 'N/A'), ('D', 'Docente'), ('A', 'Administrativo'), ('O', 'Obrero'), ('C', 'Cocinera')], max_length=3)),
                ('cod_dependency', models.CharField(max_length=20)),
                ('code_Dea', models.CharField(max_length=20)),
                ('instDependency', models.CharField(max_length=80)),
                ('hours', models.IntegerField()),
                ('admission_date', models.DateField()),
                ('bachelor', models.BooleanField(default=True)),
                ('pre_grade', models.CharField(max_length=100)),
                ('post_graduate', models.CharField(max_length=100)),
                ('other_studies', models.CharField(max_length=100)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.personal')),
            ],
        ),
    ]
